### ISSUE TITLE
Quick Start link broken on README

### ISSUE THREAD

**Issue by railroadmanuk** [rubrikinc/rubrik-cookbook-for-chef#2]
---
name: Bug Report
about: Report a bug encountered while using the Rubrik SDK for Python.
title: ''
labels: kind-bug
assignees: ''

---

**Expected Behavior**

Link to quick start on README links to quick start guide

**Current Behavior**

Link incorrect, this should be `https://github.com/rubrikinc/rubrik-cookbook-for-chef/blob/master/docs/quick-start.md`, but is set to `https://github.com/rubrikinc/rubrik-cookbook-for-chef/blob/master/docs/QUICKSTART.md`

**Failure Information (for bugs)**

n/a

**Steps to Reproduce**

n/a

**Context**

n/a

**Failure Logs**

n/a

**Comment by pmilano1** [comment]
Just seeing this now, but it was PR'd.
